spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:reward
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    format_sql: false
    hibernate:
      ddl-auto: create-drop
    show_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: embedded
